### ISSUE TITLE
ftmDataFormat for direct convolution is wrong in convolution_transform_filter_fp16

### ISSUE THREAD

**Issue by PsyDuckk** [huawei-noah/bolt#3]
ftmDataFormat for CONVOLUTION_ALGORITHM_DIRECT should be DF_NCHWN16.
[https://github.com/huawei-noah/bolt/blob/master/tensor_computing/src/cpu/arm/fp16/convolution_transform_fp16.h#L194](url)

**Comment by jianfeifeng** [comment]
Thanks for your reminder, that was the bug when refactoring our code. We have fixed it, and you can refer to the latest code [tensor_computing/src/cpu/arm/fp16/convolution_transform_fp16.h](https://github.com/huawei-noah/bolt/blob/master/tensor_computing/src/cpu/arm/fp16/convolution_transform_fp16.h) . By the way, we recommend you to use the implement of gemm to reach high performance computing instead of using the direct implement method. Thank you again!

Best Regards!
The Bolt Team.
